#######################################################
# 
# Cliente.py
# Python implementation of the Class Cliente
# Generated by Enterprise Architect
# Created on:      19-may.-2017 04:14:55 p. m.
# Original author: Luis Fernando Gomez Alejandre
# 
#######################################################


class Cliente:
    __correoElectronico = ""
    __CURP = ""
    __dirreccion = ""
    __fechaNacimiento = ""
    __nombre = ""
    __telefono = 0