#######################################################
# 
# Paquete.py
# Python implementation of the Class Paquete
# Generated by Enterprise Architect
# Created on:      19-may.-2017 04:15:58 p. m.
# Original author: Luis Fernando Gomez Alejandre
# 
#######################################################


class Paquete:
    __alto = 0
    __ancho = 0
    __cliente = None
    __largo = 0
    __numeroGuia = 0